django/zhkh_service/web/urls.py
from django.urls import path, include

from web.serializers import IndicationSerializer
from web.views import AboutPortalAPIView, ContactAPIView, NewsListAPIView, ServiceAPIView, DocumentsSerializerAPIView, \
    CountersAPIView, LivingAreaDataAPIView, TariffsAPIView, ReceiptListAPIView, yookassa_request, PaymentWidgetView, \
    PaymentSuccessView, \
    YooKassaCallbackView, PaymentSumAPIView, PaymentHistoryListAPIView, AppealCreateAPIView, AppealListAPIView, \
    IndicationsHistory, ServiceCreateAPIView, NewsCreateAPIView

app_name = 'web'

urlpatterns = [
    path('news/', NewsListAPIView.as_view(), name='news-list'),
    path('services/', ServiceAPIView.as_view(), name='service-list'),
    path('contacts/', ContactAPIView.as_view(), name='contact-list'),
    path('about-portal/', AboutPortalAPIView.as_view(), name='about-portal'),
    path('documents/', DocumentsSerializerAPIView.as_view(), name='documents'),
    path('set-counters/', CountersAPIView.as_view(), name='set-counters'),
    path('get-living-area-data/', LivingAreaDataAPIView.as_view(), name='living-area-data'),
    path('tariffs/', TariffsAPIView.as_view(), name='tariffs'),
    path('receipts/', ReceiptListAPIView.as_view(), name='receipts'),
    path('get-living-area-data/', LivingAreaDataAPIView.as_view(), name='living-area-data'),
    path('indications-history/<str:token>/', IndicationsHistory.as_view(), name='indications-history'),

    path('get-sum-payment/<str:token>/', PaymentSumAPIView.as_view(), name='get-sum-payment'),

    path('pay/', include([
        path('yk/<int:value>/', yookassa_request, name='pay'),
        path('wg/<str:ct_token>/<str:uuid>/', PaymentWidgetView.as_view(), name='payment_widget'),
        path('success/<int:pk>/', PaymentSuccessView.as_view(payment_success=True), name='payment_success'),
        path('success/<int:pk>/', PaymentSuccessView.as_view(payment_success=False), name='payment_fail'),
        path('payment-history/<str:token>/', PaymentHistoryListAPIView.as_view(), name='payment-history'),
    ])),
    path('ykcb/', YooKassaCallbackView.as_view(), name='yookassa_callback'),
    path('appeal-create/', AppealCreateAPIView.as_view(), name='appeal-create'),
    path('appeals/<str:token>/', AppealListAPIView.as_view(), name='appeal-list'),

    path('service-create/', ServiceCreateAPIView.as_view(), name='service-create'),
    path('news-create/', NewsCreateAPIView.as_view(), name='news-create'),
]

django/zhkh_service/zhkh_service/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import PasswordResetConfirmView
from django.urls import include, path

from web.views import PasswordResetCompleteCustomView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),
    path('auth/', include('djoser.urls.jwt')),

    path('password/reset/confirm/<str:uidb64>/<str:token>/', PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password/reset/complete/', PasswordResetCompleteCustomView.as_view(), name='password_reset_complete'),
    path('accounts/', include('accounts.urls')),
    path('communication/', include('communication.urls')),
    path('web/', include('web.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django/zhkh_service/web/templates/web/order_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Оплата</title>
</head>
<body>
    <div class="wrapper" style="margin-left: 78px;">
    <div class="paydetail-wrapper">
      <div class="paydetail-content">
        <div class="paydetail-content__colums">
          <div>
            <p>Номер платежа: {{ object.pk }}</p>
          </div>
          <div>
            <p>Дата оплаты: {{ object.date_created }}</p>
          </div>
          <div>
            <p>Пользователь: {{ request.user.profile }}</p>
          </div>
          <div>
            <p>Сумма к оплате: {{ object.order_amount }} руб.</p>
          </div>

          <div class="paydetail-content__paybtn">
            {% if view.payment_success %}
              <div class="paydetail-content__succes">
                <p>Оплата прошла успешно!</p>
              </div>
            {% elif view.payment_failed %}
              <div class="paydetail-content__succes">
                <p>При оплате возникла ошибка</p>
              </div>
            {% else %}
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

django/zhkh_service/web/templates/web/yookassa_pay.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Оплата</title>
</head>
<body>
    <script src="https://yookassa.ru/checkout-widget/v1/checkout-widget.js"></script>
    <div id="payment-form"></div>

    <script>
      const checkout = new window.YooMoneyCheckoutWidget({
          confirmation_token: '{{ ct_token }}',
          error_callback: function (error) {
              console.log(error)
          }
      });
      checkout.on('success', () => {
          window.location.href = '{% url 'web:payment_success' pk=payment.pk %}';
      });

      checkout.on('fail', () => {
          window.location.href = '{% url 'web:payment_fail' pk=payment.pk %}';
      });
      checkout.render('payment-form');
    </script>
</body>
</html>